window.CONVERSE_ASSETS = [
  {
    "code": "E01",
    "category": "enfants",
    "title": "Le regard attentif",
    "subtitle": "Garçon · 13 ans · boucles brunes",
    "aspectRatio": "1:1",
    "model": "nano-banana-2",
    "filename": "assets/E01.png",
    "status": "generated",
    "titleEn": "The attentive gaze",
    "subtitleEn": "Boy · 13 years old · brown curls"
  },
  {
    "code": "E02",
    "category": "enfants",
    "title": "La douceur curieuse",
    "subtitle": "Garçon · 12 ans · cheveux courts",
    "aspectRatio": "1:1",
    "model": "nano-banana-2",
    "filename": "assets/E02.png",
    "status": "generated",
    "titleEn": "Gentle curiosity",
    "subtitleEn": "Boy · 12 years old · short hair"
  },
  {
    "code": "E03",
    "category": "enfants",
    "title": "La malice discrète",
    "subtitle": "Garçon · 14 ans · mèche noire",
    "aspectRatio": "1:1",
    "model": "nano-banana-2",
    "filename": "assets/E03.png",
    "status": "generated",
    "titleEn": "A hint of mischief",
    "subtitleEn": "Boy · 14 years old · black fringe"
  },
  {
    "code": "E04",
    "category": "enfants",
    "title": "Le calme assuré",
    "subtitle": "Fille · 13 ans · boucles au menton",
    "aspectRatio": "1:1",
    "model": "nano-banana-2",
    "filename": "assets/E04.png",
    "status": "generated",
    "titleEn": "Quiet confidence",
    "subtitleEn": "Girl · 13 years old · chin-length curls"
  },
  {
    "code": "E05",
    "category": "enfants",
    "title": "Le regard joueur",
    "subtitle": "Fille · 12 ans · cheveux attachés",
    "aspectRatio": "1:1",
    "model": "nano-banana-2",
    "filename": "assets/E05.png",
    "status": "generated",
    "titleEn": "Playful eyes",
    "subtitleEn": "Girl · 12 years old · tied-back hair"
  },
  {
    "code": "E06",
    "category": "enfants",
    "title": "La franchise tendre",
    "subtitle": "Fille · 14 ans · carré cuivré",
    "aspectRatio": "1:1",
    "model": "nano-banana-2",
    "filename": "assets/E06.png",
    "status": "generated",
    "titleEn": "Tender honesty",
    "subtitleEn": "Girl · 14 years old · copper bob"
  },
  {
    "code": "G01",
    "category": "grands-peres",
    "title": "L’humour tranquille",
    "subtitle": "72 ans · boucles argentées · moustache",
    "aspectRatio": "1:1",
    "model": "nano-banana-2",
    "filename": "assets/G01.png",
    "status": "generated",
    "titleEn": "Quiet wit",
    "subtitleEn": "72 years old · silver curls · moustache"
  },
  {
    "code": "G02",
    "category": "grands-peres",
    "title": "Les yeux rieurs",
    "subtitle": "70 ans · crâne rasé · barbe blanche",
    "aspectRatio": "1:1",
    "model": "nano-banana-2",
    "filename": "assets/G02.png",
    "status": "generated",
    "titleEn": "Smiling eyes",
    "subtitleEn": "70 years old · shaved head · white beard"
  },
  {
    "code": "G03",
    "category": "grands-peres",
    "title": "La tendresse pudique",
    "subtitle": "76 ans · cheveux argentés · visage fin",
    "aspectRatio": "1:1",
    "model": "nano-banana-2",
    "filename": "assets/G03.png",
    "status": "generated",
    "titleEn": "Unspoken affection",
    "subtitleEn": "76 years old · silver hair · fine features"
  },
  {
    "code": "G04",
    "category": "grands-peres",
    "title": "L’esprit joueur",
    "subtitle": "68 ans · cheveux ondulés · barbe grise",
    "aspectRatio": "1:1",
    "model": "nano-banana-2",
    "filename": "assets/G04.png",
    "status": "generated",
    "titleEn": "A playful spirit",
    "subtitleEn": "68 years old · wavy hair · grey beard"
  },
  {
    "code": "P01",
    "category": "paires",
    "title": "Noir réparé",
    "subtitle": "Toile noire · reprise écrue · patine modérée",
    "aspectRatio": "1:1",
    "note": "Étude de couleur et de patine ; détails produit à contrôler avant le film.",
    "model": "nano-banana-2",
    "filename": "assets/P01.png",
    "status": "generated",
    "titleEn": "Mended black",
    "subtitleEn": "Black canvas · ecru stitching · gently worn",
    "noteEn": "Colour and wear study; product details need checking before the film."
  },
  {
    "code": "P02",
    "category": "paires",
    "title": "Écru dessiné",
    "subtitle": "Toile écrue · dessin bleu discret",
    "aspectRatio": "1:1",
    "note": "Étude de couleur et de patine ; détails produit à contrôler avant le film.",
    "model": "nano-banana-2",
    "filename": "assets/P02.png",
    "status": "generated",
    "titleEn": "Sketched ecru",
    "subtitleEn": "Ecru canvas · subtle blue drawing",
    "noteEn": "Colour and wear study; product details need checking before the film."
  },
  {
    "code": "P03",
    "category": "paires",
    "title": "Rouge fané",
    "subtitle": "Toile rouge brique · lacets crème",
    "aspectRatio": "1:1",
    "note": "Étude de couleur et de patine ; détails produit à contrôler avant le film.",
    "model": "nano-banana-2",
    "filename": "assets/P03.png",
    "status": "generated",
    "titleEn": "Faded red",
    "subtitleEn": "Brick-red canvas · cream laces",
    "noteEn": "Colour and wear study; product details need checking before the film."
  },
  {
    "code": "P04",
    "category": "paires",
    "title": "Marine délavé",
    "subtitle": "Toile bleu nuit · couture visible",
    "aspectRatio": "1:1",
    "note": "Étude de couleur et de patine ; détails produit à contrôler avant le film.",
    "model": "nano-banana-2",
    "filename": "assets/P04.png",
    "status": "generated",
    "titleEn": "Weathered navy",
    "subtitleEn": "Midnight-blue canvas · visible stitching",
    "noteEn": "Colour and wear study; product details need checking before the film."
  },
  {
    "code": "D01",
    "title": "Grenier de campagne · matin",
    "subtitle": "Bois chaud · lumière douce",
    "category": "ambiances",
    "aspectRatio": "16:9",
    "model": "nano-banana-2",
    "filename": "assets/D01.png",
    "status": "generated",
    "titleEn": "Country attic · morning",
    "subtitleEn": "Warm timber · soft light"
  },
  {
    "code": "D02",
    "category": "ambiances",
    "title": "Grenier de campagne · soir",
    "subtitle": "Même décor D01 · soleil doré",
    "aspectRatio": "16:9",
    "model": "nano-banana-2",
    "filename": "assets/D02.png",
    "status": "generated",
    "titleEn": "Country attic · evening",
    "subtitleEn": "Same setting as D01 · golden sunlight"
  },
  {
    "code": "D03",
    "title": "Mansarde urbaine · couvert",
    "subtitle": "Plâtre clair · lumière diffuse",
    "category": "ambiances",
    "aspectRatio": "16:9",
    "model": "nano-banana-2",
    "filename": "assets/D03.png",
    "status": "generated",
    "titleEn": "City attic · overcast",
    "subtitleEn": "Pale plaster · diffused light"
  },
  {
    "code": "D04",
    "category": "ambiances",
    "title": "Mansarde urbaine · fin de jour",
    "subtitle": "Même décor D03 · chaleur rasante",
    "aspectRatio": "16:9",
    "model": "nano-banana-2",
    "filename": "assets/D04.png",
    "status": "generated",
    "titleEn": "City attic · late afternoon",
    "subtitleEn": "Same setting as D03 · warm low light"
  },
  {
    "code": "D05",
    "title": "Grenier d’atelier · après-midi",
    "subtitle": "Brique ancienne · lumière latérale",
    "category": "ambiances",
    "aspectRatio": "16:9",
    "model": "nano-banana-2",
    "filename": "assets/D05.png",
    "status": "generated",
    "titleEn": "Workshop attic · afternoon",
    "subtitleEn": "Old brick · side lighting"
  },
  {
    "code": "D06",
    "category": "ambiances",
    "title": "Grenier d’atelier · ciel gris",
    "subtitle": "Même décor D05 · douceur froide",
    "aspectRatio": "16:9",
    "model": "nano-banana-2",
    "filename": "assets/D06.png",
    "status": "generated",
    "titleEn": "Workshop attic · grey skies",
    "subtitleEn": "Same setting as D05 · soft cool light"
  },
  {
    "code": "S00",
    "category": "styles",
    "titleEn": "The common scene",
    "subtitleEn": "Photographic reference · controlled comparison",
    "noteEn": "Same E04 child, P01 shoes and D02 attic. Provisional casting used to compare visual treatments. The camera approaches the shoes; the child’s gaze follows a stitch before the transition into memory.",
    "filename": "assets/S00.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9",
    "title": "La scène commune",
    "subtitle": "Référence photographique · comparaison contrôlée",
    "note": "Même enfant E04, même paire P01, même grenier D02. Casting provisoire, utilisé pour comparer les traitements visuels. La caméra s’approche de la paire ; le regard de l’enfant suit une couture avant le passage au souvenir."
  },
  {
    "code": "S01",
    "category": "styles",
    "titleEn": "Memories in oil",
    "subtitleEn": "Expressive painting · living impasto",
    "noteEn": "Light and wear become brushstrokes. A warm direction for memories to emerge through the material. Wear marks extend into brushstrokes and gradually repaint the attic in the colors of a memory.",
    "filename": "assets/S01.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9",
    "title": "La mémoire à l’huile",
    "subtitle": "Peinture expressive · empâtements vivants",
    "note": "La lumière et les traces d’usure deviennent des touches de peinture. Une piste chaleureuse pour faire surgir les souvenirs dans la matière. Les traces d’usure s’étirent en coups de pinceau et repeignent peu à peu le grenier dans les couleurs d’un souvenir."
  },
  {
    "code": "S02",
    "category": "styles",
    "titleEn": "Memories in halftone",
    "subtitleEn": "2.5D animation · comic-book energy",
    "noteEn": "Animation grammar inspired by Spider-Verse: halftones, graphic shapes and offset inks applied to an intimate moment. A pulse of halftone becomes a cut between eras; small ink offsets accompany the moving laces.",
    "filename": "assets/S02.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9",
    "title": "Les souvenirs en trames",
    "subtitle": "Animation 2,5D · énergie de bande dessinée",
    "note": "Une grammaire d’animation inspirée de Spider-Verse : trames, aplats et décalages d’encre, appliquée à un moment intime. Le battement d’une trame devient un raccord entre les époques ; quelques décalages d’encre accompagnent le mouvement des lacets."
  },
  {
    "code": "S03",
    "category": "styles",
    "titleEn": "Threads of inheritance",
    "subtitleEn": "Woven canvas · embroidery · textile memory",
    "noteEn": "The whole world grows from the shoes’ canvas. Colored threads connect the pair to the trunk: inheritance becomes a visible material. A thread emerges from the repair, reaches the photograph, then weaves the setting of the past around the child.",
    "filename": "assets/S03.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9",
    "title": "Les fils de la transmission",
    "subtitle": "Toile tissée · broderie · mémoire textile",
    "note": "Le monde entier naît de la toile des Converse. Des fils colorés relient la paire à la malle : la transmission devient une matière visible. Un fil sort de la reprise, rejoint la photographie puis tisse le décor du passé autour de l’enfant."
  },
  {
    "code": "S04",
    "category": "styles",
    "titleEn": "The album comes alive",
    "subtitleEn": "Torn paper · cut-out photographs",
    "noteEn": "A dimensional family album. Layers of paper make time tangible and offer natural transitions between eras. The photograph unfolds into layers of paper; the attic cutouts slide apart to reveal the earlier scene.",
    "filename": "assets/S04.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9",
    "title": "L’album prend vie",
    "subtitle": "Papiers déchirés · photographies découpées",
    "note": "Un album familial en volume. Les strates de papier matérialisent le temps et permettent de passer naturellement d’une époque à l’autre. La photographie se déplie en couches de papier ; les découpes du grenier glissent pour révéler la scène ancienne."
  },
  {
    "code": "S05",
    "category": "styles",
    "titleEn": "Three inks, three generations",
    "subtitleEn": "Risograph · ultramarine, coral, ochre",
    "noteEn": "A graphic direction: three inks, grain and simple contours. The shoe’s identity remains immediate. The three inks print in succession; each pass introduces a new generation within the same movement.",
    "filename": "assets/S05.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9",
    "title": "Trois encres, trois générations",
    "subtitle": "Risographie · outremer, corail, ocre",
    "note": "Une piste très graphique : trois encres, du grain et des contours simples. L’identité de la chaussure reste immédiate. Les trois encres s’impriment successivement ; chaque passage fait apparaître une nouvelle génération dans le même mouvement."
  },
  {
    "code": "S06",
    "category": "styles",
    "titleEn": "Color returns",
    "subtitleEn": "Charcoal present · watercolor memory",
    "noteEn": "The attic is drawn in charcoal. Amber color begins at the shoes and spreads into the room: an immediately readable story transition. At her touch, watercolor blooms from the shoes and spreads: memory returns color to the drawing.",
    "filename": "assets/S06.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9",
    "title": "La couleur revient",
    "subtitle": "Fusain du présent · aquarelle du souvenir",
    "note": "Le grenier est dessiné au fusain. Une couleur ambrée naît de la paire et gagne la pièce : une transition narrative immédiatement lisible. À son contact, une tache d’aquarelle naît de la paire et se propage : le souvenir rend ses couleurs au dessin."
  },
  {
    "code": "S07",
    "category": "styles",
    "titleEn": "Imprints of time",
    "subtitleEn": "Cyanotype · Prussian blue · golden light",
    "noteEn": "The attic becomes a handmade photographic print. Deep blue evokes the archive; gold carries the memory. The print develops in the light; golden traces connect the laces to the grandfather’s image.",
    "filename": "assets/S07.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9",
    "title": "Les empreintes du temps",
    "subtitle": "Cyanotype · bleu de Prusse · lumière dorée",
    "note": "Le grenier devient un tirage photographique artisanal. Le bleu profond évoque l’archive ; l’or fait circuler la mémoire. Le tirage se révèle à la lumière ; les traces dorées relient les lacets à l’image du grand-père."
  },
  {
    "code": "S08",
    "category": "styles",
    "titleEn": "Objects remember everything",
    "subtitleEn": "Stop motion · clay and felt puppet",
    "noteEn": "A handmade miniature with a clay-sculpted heroine dressed in felt. A lace loosens frame by frame; a match cut connects the child’s gesture with the grandfather’s.",
    "filename": "assets/S08.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9",
    "title": "Les objets gardent tout",
    "subtitle": "Stop motion · marionnette d’argile et de feutrine",
    "note": "Une miniature fabriquée à la main, avec une héroïne sculptée en argile et habillée de feutrine. Un lacet se dénoue image par image ; le geste de l’enfant retrouve celui du grand-père dans un raccord de mouvement."
  },
  {
    "code": "T01",
    "category": "equipe",
    "group": "story",
    "titleEn": "The attic box",
    "subtitleEn": "2026 · Luna, 15",
    "noteEn": "Hypothesis: a quiet discovery shifts Luna's guarded expression toward tenderness. Possible animation: slow push-in, dust in sunlight, a hand on the shoe collar; not tested. Still review: tiny collar initials are imperfect and a stray forearm mark appears; clean up if selected.",
    "filename": "assets/T01.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9",
    "title": "La boîte du grenier",
    "subtitle": "2026 · Luna, 15 ans",
    "note": "Hypothèse : une découverte silencieuse fait passer la réserve de Luna vers la tendresse. Animation possible : lent travelling avant, poussière dans le soleil, main sur le col de la chaussure ; non testée. Observation image : les petites initiales du col ne sont pas exactes et une marque parasite apparaît sur l'avant-bras ; à nettoyer si retenu."
  },
  {
    "code": "T02",
    "category": "equipe",
    "group": "story",
    "titleEn": "The first step",
    "subtitleEn": "1970 · Rafa, 15 · Bronx",
    "noteEn": "Hypothesis: a basketball pivot establishes the story's movement motif. Possible animation: one simple pivot and bounce, ground-level camera; motion continuity not tested. Still review: new shoes and court geometry read clearly; video consistency remains unverified.",
    "filename": "assets/T02.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9",
    "title": "Le premier pas",
    "subtitle": "1970 · Rafa, 15 ans · Bronx",
    "note": "Hypothèse : le pivot de basket donne le motif gestuel du récit. Animation possible : un pivot simple et un rebond, caméra au sol ; continuité du mouvement non testée. Observation image : chaussures neuves et géométrie du terrain lisibles ; cohérence vidéo encore non vérifiée."
  },
  {
    "code": "T03",
    "category": "equipe",
    "group": "story",
    "titleEn": "The same rhythm",
    "subtitleEn": "1977 · Rafa and Elena, 22",
    "noteEn": "Hypothesis: basketball footwork becomes salsa and a first encounter. Possible animation: a side step and exchanged looks; choreography and hands not tested. Still review: both dancers wear Chucks; clarify which pair carries the inheritance story and verify salsa footwork.",
    "filename": "assets/T03.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9",
    "title": "Le même rythme",
    "subtitle": "1977 · Rafa et Elena, 22 ans",
    "note": "Hypothèse : le jeu de jambes du basket devient salsa et première rencontre. Animation possible : un pas latéral et un échange de regards ; chorégraphie et mains non testées. Observation image : les deux danseurs portent des Chucks ; préciser quelle paire raconte la transmission et vérifier le pas de salsa."
  },
  {
    "code": "T04",
    "category": "equipe",
    "group": "story",
    "titleEn": "Pretending not to notice",
    "subtitleEn": "1995 · Rafa, 40 · his daughter, 17",
    "noteEn": "Hypothesis: a restrained smile conveys affection from a quiet father. Possible animation: a glance at the shoes followed by a small smile; aging and acting not tested. Still review: father-daughter tenderness reads clearly; lock facial aging and degree of wear.",
    "filename": "assets/T04.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9",
    "title": "L'air de ne pas y toucher",
    "subtitle": "1995 · Rafa, 40 ans · sa fille, 17 ans",
    "note": "Hypothèse : un sourire retenu transmet l'affection d'un père peu bavard. Animation possible : regard vers les chaussures puis discret sourire ; vieillissement et jeu non testés. Observation image : tendresse père-fille lisible ; vieillissement facial et degré d'usure à verrouiller."
  },
  {
    "code": "T05",
    "category": "equipe",
    "group": "story",
    "titleEn": "The court remembers",
    "subtitleEn": "2026 · Luna returns to the court",
    "noteEn": "Hypothesis: skate footwork echoes Rafa's pivot in the same aged location. Possible animation: one push then a short glide; spatial and motion match not tested. Still review: location closely matches the 1970 court and Luna is recognizable; shoes appear too new for the inherited pair.",
    "filename": "assets/T05.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9",
    "title": "Le terrain se souvient",
    "subtitle": "2026 · Luna retrouve le terrain",
    "note": "Hypothèse : le skate reprend le pivot de Rafa dans le même décor, vieilli. Animation possible : une poussée au sol puis glisse courte ; raccord spatial et transfert de mouvement non testés. Observation image : décor proche du terrain de 1970 et Luna reconnaissable ; les chaussures paraissent trop neuves pour la paire héritée."
  },
  {
    "code": "T06",
    "category": "equipe",
    "group": "story",
    "titleEn": "What AI cannot know",
    "subtitleEn": "Alternative opening · the cemetery",
    "noteEn": "Alternative hypothesis: an empty phone answer starts the family search. Possible animation: rack focus from the phone to Luna and the grave; lock text readability in compositing. Corrected still review: Luna holds her own phone, viewed over her shoulder, wearing ordinary low tops before the discovery. Phrases are readable but small; plan a phone insert or final composited text.",
    "filename": "assets/T06.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9",
    "title": "Ce que l'IA ne sait pas",
    "subtitle": "Ouverture alternative · le cimetière",
    "note": "Hypothèse alternative : une réponse vide sur le téléphone ouvre la quête familiale. Animation possible : mise au point du téléphone vers Luna et la tombe ; lisibilité à verrouiller en compositing. Observation image corrigée : Luna tient son propre téléphone, cadrage par-dessus son épaule, chaussures basses ordinaires avant la découverte. Les phrases sont lisibles mais petites ; prévoir un insert ou texte final en compositing."
  },
  {
    "code": "T07",
    "category": "equipe",
    "group": "future",
    "titleEn": "2050 · still the same pair",
    "subtitleEn": "Alternative concept · Luna, 39",
    "noteEn": "A separate concept from the family film: repaired shoes pass to a new generation, with a humble robot helping. Possible animation: a human handover of the pair, quiet robot support; not tested. Still review: Luna reads older than 39, only one shoe is visible in the handover, and the robot has a simplified face; refine this direction.",
    "filename": "assets/T07.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9",
    "title": "2050 · encore les mêmes",
    "subtitle": "Concept alternatif · Luna, 39 ans",
    "note": "Piste distincte du film familial : les chaussures réparées passent à une nouvelle génération, avec un robot humble en soutien. Animation possible : transmission humaine de la paire, robot discret ; non testée. Observation image : Luna paraît plus âgée que 39 ans, une seule chaussure est visible dans la transmission et le robot a un visage simplifié ; piste à préciser."
  },
  {
    "code": "T08",
    "category": "equipe",
    "group": "story",
    "titleEn": "I add my name",
    "subtitleEn": "Possible ending · R.M. + L.M.",
    "noteEn": "Ending hypothesis: Luna adds her initials beside Rafa's inside the same pair's collar. Possible animation: a final pen stroke and slight push-in; action not tested, lock lettering in compositing. Still review: R.M. and L.M. are readable inside the collar, but a stray mark is repeated on the forearm; clean up skin and refine the final pen position.",
    "filename": "assets/T08.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9",
    "title": "J'ajoute mon nom",
    "subtitle": "Fin possible · R.M. + L.M.",
    "note": "Hypothèse de fin : Luna ajoute ses initiales à celles de Rafa dans le col de la même paire. Animation possible : un dernier trait de stylo et un léger resserrement ; geste non testé, lettrage à verrouiller en compositing. Observation image : R.M. et L.M. sont lisibles dans le col, mais une marque parasite est répétée sur l'avant-bras ; nettoyer la peau et affiner la position finale du stylo."
  },
  {
    "code": "U01",
    "category": "equipe",
    "group": "team-styles",
    "titleEn": "Ink memory",
    "subtitleEn": "2D animation · Graphic monochrome",
    "noteEn": "A slight ink-line tremble, a few drawn dust particles and a lowering gaze could carry the emotion. Still-image exploration: motion and the stability of Converse details remain untested.",
    "filename": "assets/U01.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9",
    "title": "Mémoire à l’encre",
    "subtitle": "Animation 2D · Noir et blanc graphique",
    "note": "Une vibration légère du trait, quelques poussières dessinées et un regard qui s’abaisse pourraient porter l’émotion. Image de recherche : le mouvement et la tenue des détails Converse restent à tester."
  },
  {
    "code": "U02",
    "category": "equipe",
    "group": "team-styles",
    "titleEn": "Expressive 3D",
    "subtitleEn": "Animated feature · Cinematic soft focus",
    "noteEn": "A slow camera move, breathing in the shoulders and a gentle focus transition from face to shoe could create intimacy. Proposed still rendering: blur and animation need validation in a moving shot.",
    "filename": "assets/U02.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9",
    "title": "3D sensible",
    "subtitle": "Long métrage animé · Flou cinématographique",
    "note": "Un lent mouvement d’approche, la respiration des épaules et une transition douce du visage vers la chaussure pourraient créer l’intimité. Proposition de rendu fixe : flou et animation à valider sur un plan."
  },
  {
    "code": "U03",
    "category": "equipe",
    "group": "team-styles",
    "titleEn": "Real-time cinematic",
    "subtitleEn": "Contemporary narrative game · Tangible materials",
    "noteEn": "A very slow shoulder-height camera and a fleeting expression change could bring the viewer closer to Luna. Still art-direction study: real-time lighting and character continuity need to be tested in motion.",
    "filename": "assets/U03.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9",
    "title": "Cinématique temps réel",
    "subtitle": "Jeu narratif contemporain · Matières tangibles",
    "note": "Une caméra très lente à hauteur d’épaule et un bref changement d’expression pourraient rapprocher le spectateur de Luna. Piste de direction artistique fixe : éclairage temps réel et continuité du personnage à éprouver en mouvement."
  },
  {
    "code": "U04",
    "category": "equipe",
    "group": "team-styles",
    "titleEn": "Painted-wood fable",
    "subtitleEn": "Handcrafted animation · Seafaring storybook textures",
    "noteEn": "Fibres, painted grain and gently wavering light could animate the attic as a tactile miniature. A free interpretation of a seafaring fable, with no specific film identified; still image, motion untested.",
    "filename": "assets/U04.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9",
    "title": "Conte de bois peint",
    "subtitle": "Animation artisanale · Matières de conte marin",
    "note": "Les fibres, le grain peint et une lumière doucement oscillante pourraient animer le grenier comme une maquette sensible. Interprétation libre d’un conte marin, sans film identifié ; image fixe, mouvement à tester."
  },
  {
    "code": "U05",
    "category": "equipe",
    "group": "team-styles",
    "titleEn": "Augmented memory 2050",
    "subtitleEn": "Experimental future style · Hybrid archive",
    "noteEn": "Luminous fragments could reconstruct the attic around a Converse that remains physical and tactile. An experimental style test distinct from the future narrative: neither animation nor the hologram system has been validated.",
    "filename": "assets/U05.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9",
    "title": "Mémoire augmentée 2050",
    "subtitle": "Style futur expérimental · Archive hybride",
    "note": "Des fragments lumineux pourraient reconstruire le grenier autour d’une Converse qui reste physique et tactile. Test de style expérimental distinct du récit futuriste : ni animation ni système d’hologrammes encore validés."
  },
  {
    "code": "H01",
    "category": "hybrides",
    "group": "looks",
    "title": "Mémoire en pixels",
    "titleEn": "Pixel memories",
    "subtitle": "Pixel art · palette réduite",
    "subtitleEn": "Pixel art · limited palette",
    "note": "Une scène de jeu narratif, en pixels nets et palette chaude. Le cadrage de T01 permet de comparer les matières.",
    "noteEn": "A narrative game scene with crisp pixels and a warm palette. T01’s framing makes material comparisons easy.",
    "filename": "assets/H01.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9"
  },
  {
    "code": "H02",
    "category": "hybrides",
    "group": "looks",
    "title": "Pixels dans la lumière",
    "titleEn": "Pixels in the light",
    "subtitle": "HD-2D · profondeur cinématographique",
    "subtitleEn": "HD-2D · cinematic depth",
    "note": "Luna et les chaussures restent en pixels ; la lumière et le flou des plans lointains créent la profondeur.",
    "noteEn": "Luna and the shoes stay pixelated; light and softly blurred distant layers add depth.",
    "filename": "assets/H02.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9"
  },
  {
    "code": "H03",
    "category": "hybrides",
    "group": "looks",
    "title": "Luna, argile et coton",
    "titleEn": "Luna, clay and cotton",
    "subtitle": "Personnage sculpté · tissus réalistes",
    "subtitleEn": "Sculpted character · realistic fabrics",
    "note": "La piste la plus proche de ta référence : visage et cheveux sculptés, vêtements réalistes. Petites lettres sur la chaussure à nettoyer si retenue.",
    "noteEn": "Closest to your reference: sculpted face and hair, realistic fabrics. Small stray letters on the shoe need cleanup if selected.",
    "filename": "assets/H03.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9"
  },
  {
    "code": "H04",
    "category": "hybrides",
    "group": "looks",
    "title": "La poussée prend forme",
    "titleEn": "A push takes shape",
    "subtitle": "Hybride d’action · skate au sol",
    "subtitleEn": "Action hybrid · grounded skating",
    "note": "Le même mélange argile et tissu en action, sur le terrain de T05. Les chaussures devront retrouver davantage de patine.",
    "noteEn": "The same clay-and-fabric mix in action on T05’s court. The shoes need more wear for the inherited-pair story.",
    "filename": "assets/H04.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9"
  },
  {
    "code": "H05",
    "category": "hybrides",
    "group": "looks",
    "title": "Trois matières, un souvenir",
    "titleEn": "Three materials, one memory",
    "subtitle": "Chaussure photo · Luna dessinée · grenier façonné",
    "subtitleEn": "Photographic shoe · illustrated Luna · crafted attic",
    "note": "Trois matières cohabitent : Converse réalistes, Luna dessinée en volume et charpente de carton. Petites marques du col à nettoyer si retenue.",
    "noteEn": "Three materials coexist: realistic Converse, dimensional illustrated Luna and cardboard rafters. Small collar marks need cleanup if selected.",
    "filename": "assets/H05.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9"
  },
  {
    "code": "X01",
    "category": "hybrides",
    "group": "transition",
    "title": "Avant le basculement",
    "titleEn": "Before the shift",
    "subtitle": "Réaliste · Luna enfile l’héritage",
    "subtitleEn": "Photorealistic · Luna steps into the inheritance",
    "note": "Avant : le grenier reste photographique, les Converse sont aux pieds. Le pied avant est encore légèrement relevé.",
    "noteEn": "Before: the attic remains photographic, with the Converse on her feet. The foreground toe is still slightly raised.",
    "filename": "assets/X01.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9"
  },
  {
    "code": "X02",
    "category": "hybrides",
    "group": "transition",
    "title": "Le contact change la matière",
    "titleEn": "Contact changes the material",
    "subtitle": "Seuil · du parquet photographié à l’encre",
    "subtitleEn": "Threshold · photographed floorboards become ink",
    "note": "Pendant : l’encre et les trames gagnent le sol depuis la chaussure. Le cadrage et le visage restent très proches de X01.",
    "noteEn": "During: ink and halftone spread across the floor from the shoe. Framing and face stay closely aligned with X01.",
    "filename": "assets/X02.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9"
  },
  {
    "code": "X03",
    "category": "hybrides",
    "group": "transition",
    "title": "Le souvenir devient animation",
    "titleEn": "Memory becomes animation",
    "subtitle": "Après · volume peint et langage bande dessinée",
    "subtitleEn": "After · painted volume and comic-book language",
    "note": "Après : la même scène devient une illustration en volume. Le rendu évoque la BD peinte ; la continuité en mouvement reste à tester.",
    "noteEn": "After: the same scene becomes a dimensional illustration. The look suggests painted comics; continuity in motion still needs testing.",
    "filename": "assets/X03.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9"
  },
  {
    "code": "L01",
    "category": "production",
    "group": "luna",
    "title": "Luna · silhouette de référence",
    "titleEn": "Luna · character turnaround",
    "subtitle": "Face · dos · portrait — tenue d’origine",
    "subtitleEn": "Front · back · portrait — original outfit",
    "note": "Face, dos et portrait de Luna en tenue d’origine. Référence pour le visage et la silhouette ; les ourlets cachent le haut des chaussures.",
    "noteEn": "Front, back and portrait of Luna in her original outfit. Face and silhouette reference; trouser hems cover the shoe collars.",
    "filename": "assets/L01.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9"
  },
  {
    "code": "L02",
    "category": "production",
    "group": "luna",
    "title": "Luna · nuances d’émotion",
    "titleEn": "Luna · emotional range",
    "subtitle": "Six expressions discrètes",
    "subtitleEn": "Six restrained expressions",
    "note": "Six expressions retenues : neutralité, curiosité, tristesse, petit sourire, concentration et soulagement. À utiliser avec la référence du visage.",
    "noteEn": "Six restrained expressions: neutral, curious, sad, small smile, focused and relieved. Use alongside the face reference.",
    "filename": "assets/L02.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9"
  },
  {
    "code": "L03",
    "category": "production",
    "group": "luna",
    "title": "Luna · l’accent orange",
    "titleEn": "Luna · the orange accent",
    "subtitle": "Du dessin à la photo — essai de costume",
    "subtitleEn": "From illustration to photograph — wardrobe test",
    "note": "Le dessin devient une photographie : visage de Luna, chignon et accessoires orange. Les bouts peints des chaussures sont une personnalisation à comparer.",
    "noteEn": "The sketch becomes a photograph: Luna’s face, high bun and orange accessories. Painted shoe toes are a customization option to compare.",
    "filename": "assets/L03.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9"
  },
  {
    "code": "L04",
    "category": "production",
    "group": "luna",
    "title": "Luna · continuité orange",
    "titleEn": "Luna · orange wardrobe continuity",
    "subtitle": "Face · dos · portrait — variation orange",
    "subtitleEn": "Front · back · portrait — orange variation",
    "note": "Face, dos et portrait de la tenue orange. La génération ajoute des touches orange aux talons : à décider avant de fixer le costume.",
    "noteEn": "Front, back and portrait of the orange outfit. The generation adds orange heel accents: decide on these before locking the costume.",
    "filename": "assets/L04.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9"
  },
  {
    "code": "L05",
    "category": "production",
    "group": "luna",
    "title": "Luna · dans le grenier D06",
    "titleEn": "Luna · inside attic D06",
    "subtitle": "Tenue d’origine · découverte des Converse",
    "subtitleEn": "Original outfit · discovering the Converse",
    "note": "Luna retrouve la paire dans le grenier D06. Fenêtre, briques et coffre conservés ; vérifier l’échelle exacte de la paire pour le plan final.",
    "noteEn": "Luna discovers the pair in attic D06. Window, brickwork and chest are preserved; check the exact shoe scale before the final shot.",
    "filename": "assets/L05.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9"
  },
  {
    "code": "G11",
    "category": "production",
    "group": "grandpa",
    "title": "Rafa · silhouette de référence",
    "titleEn": "Rafa · identity turnaround",
    "subtitle": "72 ans · face, dos et portrait",
    "subtitleEn": "Age 72 · front, back and portrait",
    "note": "Déclinaison directe de G01 : boucles argentées, moustache courte, surchemise anthracite et Converse noires. Base pour les scènes du grand-père.",
    "noteEn": "Direct development from G01: silver curls, short moustache, charcoal overshirt and black Converse. A base for the grandfather scenes.",
    "filename": "assets/G11.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9"
  },
  {
    "code": "G12",
    "category": "production",
    "group": "grandpa",
    "title": "Rafa · le jeune basketteur",
    "titleEn": "Rafa · the young basketball player",
    "subtitle": "16 ans · silhouette et visage",
    "subtitleEn": "Age 16 · silhouette and face",
    "note": "Rajeunissement proposé de G01, avec le même nez, le regard et les proportions du visage. Tenue de basket inspirée des années 1970 ; identité jeune à valider.",
    "noteEn": "Proposed age regression from G01, retaining his nose, eyes and facial proportions. Basketball clothing inspired by the 1970s; young identity remains to be approved.",
    "filename": "assets/G12.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9"
  },
  {
    "code": "G13",
    "category": "production",
    "group": "grandpa",
    "title": "Rafa · les années salsa",
    "titleEn": "Rafa · the salsa years",
    "subtitle": "23 ans · face, dos et portrait",
    "subtitleEn": "Age 23 · front, back and portrait",
    "note": "Même jeune Rafa proposé, chemise rouille à col ouvert et pantalon évasé. Références G01 et G12 pour relier les âges ; visage jeune encore exploratoire.",
    "noteEn": "The proposed young Rafa in a rust open-collar shirt and flared trousers. G01 and G12 anchor the age continuity; his younger face is still exploratory.",
    "filename": "assets/G13.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9"
  },
  {
    "code": "G14",
    "category": "production",
    "group": "grandpa",
    "title": "Rafa · le père de famille",
    "titleEn": "Rafa · the family father",
    "subtitle": "41 ans · silhouette et visage",
    "subtitleEn": "Age 41 · silhouette and face",
    "note": "Variante d'âge dérivée de G01 : boucles brunes, moustache et premières tempes grises. Cette étape de vie est une proposition de casting, sans date narrative figée.",
    "noteEn": "An age variation derived from G01: brown curls, moustache and the first greys at his temples. This life stage is a casting proposal without a locked story date.",
    "filename": "assets/G14.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9"
  },
  {
    "code": "G15",
    "category": "production",
    "group": "grandpa",
    "title": "Rafa · ce qu'il ne dit pas",
    "titleEn": "Rafa · what he leaves unsaid",
    "subtitle": "72 ans · six expressions retenues",
    "subtitleEn": "Age 72 · six restrained expressions",
    "note": "Neutre, réserve, sourire complice, amusement, tendresse et tristesse calme. Repère de jeu pour un homme peu bavard ; pas de larmes ni d'expressions théâtrales.",
    "noteEn": "Neutral, guarded, knowing smile, amusement, tenderness and quiet sadness. A performance guide for a man of few words, without tears or theatrical expressions.",
    "filename": "assets/G15.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9"
  },
  {
    "code": "R01",
    "category": "production",
    "group": "sets",
    "title": "D06 · Au niveau des chaussures",
    "titleEn": "D06 · At shoe level",
    "subtitle": "Grenier · coffre et fenêtre · angle bas",
    "subtitleEn": "Attic · trunk and window · low angle",
    "note": "Caméra au sol dans D06, près du coffre. Le tabouret est renversé dans ce test : à redresser pour conserver le raccord.",
    "noteEn": "Floor-level camera in D06, close to the chest. The stool is overturned in this test; restore it for continuity.",
    "filename": "assets/R01.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9"
  },
  {
    "code": "R02",
    "category": "production",
    "group": "sets",
    "title": "D06 · Un autre angle",
    "titleEn": "D06 · Another angle",
    "subtitle": "Grenier · angle diagonal proposé",
    "subtitleEn": "Attic · proposed diagonal angle",
    "note": "Angle diagonal proposé pour D06, avec ses repères reconnaissables. La géométrie de cet angle reste une reconstruction à valider.",
    "noteEn": "Proposed diagonal view of D06 with recognizable landmarks. The geometry of this angle is an inferred reconstruction to validate.",
    "filename": "assets/R02.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9"
  },
  {
    "code": "R03",
    "category": "production",
    "group": "sets",
    "title": "Le terrain · 1970",
    "titleEn": "The court · 1970",
    "subtitle": "Bronx · terrain vide · époque proposée",
    "subtitleEn": "Bronx · empty court · proposed period",
    "note": "Le terrain de T02 sans personnages ni ballon. Panier à gauche, arche à droite : base du raccord entre les deux générations.",
    "noteEn": "The T02 court without characters or ball. Hoop on the left, arch on the right: the base for the generational match.",
    "filename": "assets/R03.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9"
  },
  {
    "code": "R04",
    "category": "production",
    "group": "sets",
    "title": "Le même terrain · 2026",
    "titleEn": "The same court · 2026",
    "subtitle": "Raccord d’époque · patine et skate",
    "subtitleEn": "Matching eras · patina and skate",
    "note": "Même cadrage que R03, avec un petit module de skate et une patine discrète. Continuité en mouvement à tester.",
    "noteEn": "The same framing as R03, adding a small skate obstacle and restrained wear. Continuity in motion remains untested.",
    "filename": "assets/R04.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9"
  },
  {
    "code": "R05",
    "category": "production",
    "group": "sets",
    "title": "La rencontre · Salle de salsa",
    "titleEn": "The meeting · Salsa hall",
    "subtitle": "Fin des années 1970 · rouge, prune et or",
    "subtitleEn": "Late 1970s · red, plum and gold",
    "note": "Une salle de quartier vide, bois chaud et lumières rouge, prune et or. Le centre reste libre pour la rencontre et les pas de danse.",
    "noteEn": "An empty neighborhood hall with warm wood and red, plum and gold light. The center is clear for the meeting and dance steps.",
    "filename": "assets/R05.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9"
  },
  {
    "code": "R06",
    "category": "production",
    "group": "sets",
    "title": "La maison · Transmission",
    "titleEn": "The home · Passing it on",
    "subtitle": "1995 · salon familial · lumière de fenêtre",
    "subtitleEn": "1995 · family living room · window light",
    "note": "Salon familial proposé pour la scène de transmission. Le bois et la brique prolongent D06 ; petit fil au premier plan à nettoyer.",
    "noteEn": "Proposed family living room for the handover scene. Wood and brick echo D06; a small foreground cord needs cleanup.",
    "filename": "assets/R06.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9"
  },
  {
    "code": "R07",
    "category": "production",
    "group": "sets",
    "title": "Le départ · Chemin du cimetière",
    "titleEn": "The beginning · Cemetery path",
    "subtitle": "2026 · silence · lumière douce",
    "subtitleEn": "2026 · stillness · soft daylight",
    "note": "Un chemin calme et une pierre sans inscription. Un décor disponible si l’ouverture au cimetière est retenue.",
    "noteEn": "A quiet path and an unlettered gravestone. A location option if the cemetery opening is selected.",
    "filename": "assets/R07.png",
    "model": "nano-banana-2",
    "status": "generated",
    "aspectRatio": "16:9"
  }
];
