import {safeMedia} from './model.js';
import {filterVideos,groupVideos,suggestedRange,selectedVideoTake,safePoster} from './gallery-model.js';
const $=id=>document.getElementById(id),esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const time=n=>Number.isFinite(Number(n))&&Number(n)>0?`${Number(n).toFixed(1)} s`:'Durée à vérifier';
export function createGallery({getScenes,getSelectedId,onUse,onInsert,toast}){
  let assets=[],activeId=null,actualDuration=null,hoverVideo=null,hoverCard=null,hoverTimer=null,rangePlaying=false,rangeEdited=false,loading=false,lastCompleted='';
  const selected=()=>assets.find(a=>a.id===activeId),target=()=>getScenes().find(s=>s.id===$('gallery-target').value);
  function stopHover(){clearTimeout(hoverTimer);hoverTimer=null;if(hoverVideo){hoverVideo.pause();hoverVideo.removeAttribute('src');hoverVideo.load();hoverVideo.remove();}hoverCard?.classList.remove('previewing');hoverVideo=null;hoverCard=null;}
  function hover(card){if(hoverCard===card||matchMedia('(prefers-reduced-motion: reduce)').matches)return;stopHover();const asset=assets.find(a=>a.id===card.dataset.galleryAsset);if(!asset||!safeMedia(asset.url))return;hoverCard=card;hoverTimer=setTimeout(()=>{if(hoverCard!==card||!$('gallery-dialog').open)return;const video=document.createElement('video');hoverVideo=video;video.muted=true;video.defaultMuted=true;video.loop=true;video.playsInline=true;video.preload='none';video.setAttribute('aria-hidden','true');video.src=asset.url;card.querySelector('.gallery-poster').append(video);card.classList.add('previewing');video.play().catch(()=>{if(hoverVideo===video)stopHover();});},180);}
  function options(){const prior={model:$('gallery-model').value,collection:$('gallery-collection').value,scope:$('gallery-scope').value,target:$('gallery-target').value};
    $('gallery-model').innerHTML='<option value="">Tous les modèles</option>'+[...new Set(assets.map(a=>a.model).filter(Boolean))].sort().map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');
    $('gallery-collection').innerHTML='<option value="">Toutes les collections</option>'+[...new Set(assets.map(a=>a.collection).filter(Boolean))].sort().map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');
    const sceneOptions=getScenes().map((s,i)=>`<option value="${esc(s.id)}">${String(i+1).padStart(2,'0')} · ${esc(s.title)}</option>`).join('');
    $('gallery-scope').innerHTML='<option value="all">Tout le récit</option>'+sceneOptions+'<option value="group:films">Films & séquences complètes</option><option value="group:other">Autres explorations</option><option value="group:unassigned">À classer</option>';
    $('gallery-target').innerHTML=sceneOptions;
    for(const [field,value]of Object.entries(prior)){const el=$('gallery-'+field);if([...el.options].some(o=>o.value===value))el.value=value;}
  }
  function render(){stopHover();const matching=filterVideos(assets,{search:$('gallery-search').value,model:$('gallery-model').value,collection:$('gallery-collection').value,scope:$('gallery-scope').value});const groups=groupVideos(matching,getScenes(),$('gallery-scope').value);$('gallery-count').textContent=`${matching.length} / ${assets.length} vidéos`;
    $('gallery-groups').innerHTML=groups.map(group=>`<section class="gallery-group"><div class="gallery-group-title"><h3>${esc(group.name)}</h3><span>${group.items.length} prise${group.items.length>1?'s':''}</span></div><div class="gallery-cards">${group.items.map(a=>`<button class="gallery-card ${a.id===activeId?'selected':''}" data-gallery-asset="${esc(a.id)}" aria-label="Comparer ${esc(a.name)}"><span class="gallery-poster">${safePoster(a.posterUrl)?`<img src="${esc(a.posterUrl)}" alt="" loading="lazy">`:'<span class="gallery-no-poster">▷</span>'}<span class="gallery-play">▶</span><span class="gallery-length">${time(a.durationSeconds)}</span></span><span class="gallery-card-copy"><small>${esc(a.collection||'ATELIER')}</small><strong>${esc(a.name)}</strong><span>${esc(a.model||'Modèle non renseigné')}</span></span></button>`).join('')}</div></section>`).join('')||'<div class="gallery-empty"><span>✦</span><h3>Aucune vidéo dans cette sélection</h3><p>Essaie une autre scène ou efface les filtres.</p></div>';
  }
  async function fetchLibrary(refresh=false){if(loading)return;loading=true;$('gallery-refresh').disabled=true;$('gallery-message').textContent='Lecture de la vidéothèque…';try{if(refresh){const r=await fetch('/api/studio/library/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(!r.ok)throw Error('Actualisation impossible.');}const response=await fetch('/api/studio/library');const data=await response.json();if(!response.ok)throw Error(data.error||'La galerie est indisponible.');assets=(data.assets||[]).filter(a=>a.kind==='video'&&safeMedia(a.url));options();render();$('gallery-message').textContent='Survole une prise pour la voir en silence. Clique pour choisir un passage.';}catch(e){$('gallery-message').textContent=e.message;}finally{loading=false;$('gallery-refresh').disabled=false;}}
  function updateRange(){$('gallery-video').pause();rangePlaying=false;const asset=selected();if(!asset)return;let take;try{take=selectedVideoTake(asset,$('gallery-in').value,$('gallery-out').value,actualDuration);$('gallery-range-note').textContent=`${((take.outFrame-take.inFrame)/24).toFixed(2)} s retenues · le fichier source reste intact`;$('gallery-use').disabled=false;$('gallery-insert').disabled=false;}catch(e){$('gallery-range-note').textContent=e.message;$('gallery-use').disabled=true;$('gallery-insert').disabled=true;}rangePlaying=false;}
  function setSuggested(){$('gallery-video').pause();rangePlaying=false;const asset=selected();if(!asset)return;const range=suggestedRange(asset,target(),actualDuration);if(!range){$('gallery-range-note').textContent='Chargement de la durée…';$('gallery-use').disabled=true;$('gallery-insert').disabled=true;return;}for(const id of ['gallery-in','gallery-out'])$(id).max=actualDuration;$('gallery-in').value=range.inSeconds.toFixed(3);$('gallery-out').value=range.outSeconds.toFixed(3);$('gallery-mapping-note').textContent=range.mapped?'Passage identifié pour ce plan. Ajuste le début et la fin si besoin.':'Aucun passage vérifié pour ce plan : le début de la vidéo est proposé à la durée cible. Choisis ton extrait avant de l’utiliser.';if($('gallery-video').readyState>=1)$('gallery-video').currentTime=range.inSeconds;updateRange();}
  function detail(id){stopHover();const a=assets.find(a=>a.id===id);if(!a)return;activeId=id;actualDuration=Number(a.durationSeconds)||null;rangePlaying=false;rangeEdited=false;$('gallery-detail').hidden=false;$('gallery-detail-empty').hidden=true;$('gallery-detail-title').textContent=a.name;$('gallery-provenance').textContent=[a.model,a.collection,a.relativePath].filter(Boolean).join(' · ');$('gallery-classification-note').textContent=a.classificationNote||'Classement éditable ; le fichier original est conservé.';$('gallery-assignment').value=a.group||'unassigned';const scoped=getScenes().find(s=>s.id===$('gallery-scope').value);$('gallery-target').value=scoped?.id||(getScenes().some(s=>s.id===getSelectedId())?getSelectedId():getScenes()[0]?.id);const video=$('gallery-video');video.pause();video.src=a.url;if(safePoster(a.posterUrl))video.poster=a.posterUrl;else video.removeAttribute('poster');video.load();setSuggested();document.querySelectorAll('[data-gallery-asset]').forEach(card=>card.classList.toggle('selected',card.dataset.galleryAsset===id));if(matchMedia('(max-width: 670px)').matches)$('gallery-detail').scrollIntoView({block:'start',behavior:'smooth'});}
  $('gallery-video').addEventListener('loadedmetadata',()=>{const v=$('gallery-video');if(Number.isFinite(v.duration)&&v.duration>0){actualDuration=v.duration;if(rangeEdited){for(const id of ['gallery-in','gallery-out'])$(id).max=actualDuration;updateRange();}else setSuggested();}});
  $('gallery-video').addEventListener('timeupdate',()=>{const v=$('gallery-video');if(rangePlaying&&v.currentTime>=Number($('gallery-out').value)){v.pause();rangePlaying=false;v.currentTime=Number($('gallery-in').value);}});
  $('gallery-target').addEventListener('change',()=>{rangeEdited=false;setSuggested();});
  for(const id of ['gallery-in','gallery-out'])$(id).addEventListener('input',()=>{rangeEdited=true;updateRange();});
  $('gallery-play-range').addEventListener('click',()=>{try{selectedVideoTake(selected(),$('gallery-in').value,$('gallery-out').value,actualDuration);const v=$('gallery-video');v.currentTime=Number($('gallery-in').value);rangePlaying=true;v.play().catch(()=>{});}catch(e){toast(e.message);}});
  for(const [id,field]of [['gallery-mark-in','gallery-in'],['gallery-mark-out','gallery-out']])$(id).addEventListener('click',()=>{$(field).value=$('gallery-video').currentTime.toFixed(3);rangeEdited=true;updateRange();});
  function commit(insert=false){try{const asset=selected(),scene=target();if(!scene)throw Error('Choisis un plan de destination.');const take=selectedVideoTake(asset,$('gallery-in').value,$('gallery-out').value,actualDuration);if(insert)onInsert({asset,sceneId:scene.id,take});else onUse({asset,sceneId:scene.id,take});$('gallery-dialog').close();}catch(e){toast(e.message);}}
  $('gallery-use').addEventListener('click',()=>commit());$('gallery-insert').addEventListener('click',()=>commit(true));
  $('gallery-save-assignment').addEventListener('click',async()=>{const asset=selected();if(!asset)return;const button=$('gallery-save-assignment');button.disabled=true;try{const group=$('gallery-assignment').value;const payload={id:asset.id,group,sceneIds:group==='scenes'?[$('gallery-target').value]:group==='films'?(asset.sceneIds||[]):[]};const response=await fetch('/api/studio/library/assignment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),data=await response.json();if(!response.ok)throw Error(data.error||'Classement impossible.');assets=assets.map(a=>a.id===asset.id?data.asset:a);render();$('gallery-classification-note').textContent=data.asset.classificationNote||'Classement enregistré.';toast('Classement enregistré. Le montage reste inchangé.');}catch(e){toast(e.message);}finally{button.disabled=false;}});
  $('gallery-groups').addEventListener('click',e=>{const card=e.target.closest('[data-gallery-asset]');if(card)detail(card.dataset.galleryAsset);});
  $('gallery-groups').addEventListener('pointerover',e=>{const card=e.target.closest('[data-gallery-asset]');if(card&&e.pointerType!=='touch')hover(card);});
  $('gallery-groups').addEventListener('pointerout',e=>{const card=e.target.closest('[data-gallery-asset]');if(card&&card===hoverCard&&!card.contains(e.relatedTarget))stopHover();});
  $('gallery-groups').addEventListener('scroll',stopHover,{passive:true});$('gallery-dialog').addEventListener('scroll',stopHover,{passive:true});
  for(const id of ['gallery-model','gallery-collection','gallery-scope'])$(id).addEventListener('change',render);
  $('gallery-search').addEventListener('input',render);$('gallery-refresh').addEventListener('click',()=>fetchLibrary(true));
  $('gallery-close').addEventListener('click',()=>$('gallery-dialog').close());$('gallery-dialog').addEventListener('close',()=>{stopHover();$('gallery-video').pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){stopHover();$('gallery-video').pause();}});window.addEventListener('blur',stopHover);
  return {async open(sceneId=null){$('gallery-dialog').showModal();await fetchLibrary();$('gallery-scope').value=sceneId||'all';render();},jobsUpdated(jobs){const ids=jobs.filter(j=>j.status==='completed').map(j=>j.id).sort().join(',');if(ids!==lastCompleted){lastCompleted=ids;if($('gallery-dialog').open)void fetchLibrary();}}};
}
