import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {insertScene,moveScene,applyDirection,validateProject,safeMedia,generationPrompt,mergeBlocking,replaceReference,referencePrompt} from './model.js';
const raw=JSON.parse(fs.readFileSync(new URL('./project.json',import.meta.url)));
test('20 selected V4 cuts and existing reference lineage load',()=>{const p=validateProject(raw);assert.equal(p.scenes.length,20);assert.equal(p.scenes.reduce((t,s)=>t+s.duration,0),76);});
test('inserting a new scene preserves source and isolates geometry',()=>{const p=validateProject(raw),id=p.scenes[0].id;const s=insertScene(p,id,{title:'New memory'});assert.equal(p.scenes[1].id,s.id);assert.equal(s.source,undefined);s.blocking.characters[0].position[0]=99;assert.notEqual(p.scenes[0].blocking.characters[0].position[0],99);assert.equal(raw.scenes.length,20);});
test('reordering preserves source intervals',()=>{const p=validateProject(raw),s=p.scenes[0],source=JSON.stringify(s.source);assert.equal(moveScene(p,s.id,-1),false);assert.equal(moveScene(p,s.id,1),true);assert.equal(JSON.stringify(p.scenes[1].source),source);});
test('direction retains rollback and only interprets supported geometry',()=>{const s=validateProject(raw).scenes[0],before=s.prompt;const applied=applyDirection(s,'Rapproche la caméra de Luna, à gauche. Lumière chaude.');assert.ok(applied.length>=3);assert.equal(s.versions[0].prompt,before);assert.match(s.prompt,/LATEST DIRECTOR NOTE/);const beforeBlocking=JSON.stringify(s.blocking);assert.equal(applyDirection(s,'Ajoute une émotion de nostalgie.').length,0);assert.equal(JSON.stringify(s.blocking),beforeBlocking);});
test('regeneration narrows multi-scene original prompts to the selected cut',()=>{const p=generationPrompt(raw.scenes[0],'video',true);assert.match(p,/10-second video shot/);assert.match(p,/ONLY the selected shot/);assert.match(p,/composition guide ONLY/);});
test('import blocks executable and traversal media',()=>{for(const bad of ['javascript:alert(1)','data:text/html,hello','/creative/../secret','https://evil.example/x','/api/studio/jobs/nope/artifact'])assert.equal(safeMedia(bad),false);assert.equal(safeMedia('/api/studio/jobs/'+'a'.repeat(32)+'/artifact'),true);const p=structuredClone(raw);p.scenes[0].references[0].url='javascript:alert(1)';assert.throws(()=>validateProject(p));});

test('3D partial revision preserves cast; invalid placement is rejected',()=>{const b=raw.scenes[0].blocking;const merged=mergeBlocking(b,{camera:{fov:55}});assert.equal(merged.characters[0].id,b.characters[0].id);assert.equal(merged.camera.fov,55);const p=structuredClone(raw);p.scenes[0].blocking.characters=[null];assert.throws(()=>validateProject(p));assert.throws(()=>mergeBlocking(b,{characters:[{id:'a',position:'bad'}]}));});

test('asset changes isolate one reference and preserve original for restoration',()=>{const p=validateProject(raw),s=p.scenes[0],r=s.references[0],original=r.url;const other=structuredClone(p.scenes[1]);const replacement='/api/studio/jobs/'+'b'.repeat(32)+'/artifact';replaceReference(s,r.id,{url:replacement});assert.equal(s.references[0].url,replacement);assert.equal(s.referenceVersions[r.id][0].url,original);assert.deepEqual(p.scenes[1],other);assert.match(referencePrompt(s,r,'Change only the laces'),/single asset/);assert.throws(()=>replaceReference(s,r.id,{url:'javascript:evil()'}));});
