import {createProject,validateProject,timeline,locate,splitSegment,setSource,trimSegment,removeSegment,moveSegment,durationFrames,formatTime} from './model.js';

const $=id=>document.getElementById(id);
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='converse-cut-room-v1',LANG='converse-board-language';
const names={veo31:'Veo 3.1',kling3:'Kling 3 Pro',seedance25:'Seedance 2.5'};
const order=['veo31','kling3','seedance25'];
const labels=[['Opening','Ouverture'],['The attic','Le grenier'],['The shoebox','La boîte'],['A question','Une question'],['The laces','Les lacets'],['First memory','Premier souvenir'],['The shot','Le tir'],['The basket','Le panier'],['A private smile','Le sourire'],['The first step','Le premier pas'],['Meeting Elena','Rencontre avec Elena'],['The wedding','Le mariage'],['A new family','Une famille'],['The gift','La transmission'],['Back to Luna','Retour à Luna'],['Tell me about him','Raconte-moi'],["Mom’s smile",'Le sourire de maman'],['What matters','Ce qui compte']];
const boundaries=[0,144,240,360,528,624,696,780,816,864,936,1128,1224,1320,1512,1584,1680,1728,1824];
const strings={
 en:{eyebrow:'THREE MODELS. YOUR CUT.',heading:'Keep the moments that matter.',intro:'Compare the same moment. Pick a take. Make it yours.',import:'Open edit',save:'Save edit',compare:'Compare',program:'Your film',soundOn:'Sound on',soundOff:'Sound off',fit:'Fit timeline',timeline:'THE EDIT',split:'Split at playhead',zoom:'Zoom',sources:'SOURCE TAKES',yourCut:'YOUR CUT',sharedAudio:'SHARED AUDIO',audioDetail:'One consistent soundtrack · music + dialogue',timelineHint:'Click a take to use it. Drag the ruler to compare a moment.',previewHint:'Preview is approximate; export cuts on exact frames.',selectedShot:'SELECTED SHOT',take:'TAKE',sourceIn:'SOURCE IN',sourceOut:'SOURCE OUT',applyTrim:'Apply trim',markIn:'Set in [I]',markOut:'Set out [O]',trimHint:'Timecode: minutes:seconds:frames. End frame is excluded.',earlier:'← Earlier',later:'Later →',remove:'Remove shot',defaultNote:'Veo is your starting point. You can replace any passage without changing the others.',reset:'Reset to all Veo',backBoard:'Back to the visual board ↗',localNote:'Edits stay in this browser. Save a JSON edit to share with your team.',exportEyebrow:'MAKE IT A FILM',exportTitle:'Your best takes, together.',render:'Render MP4',download:'Download film ↓',downloadRecipe:'Download edit recipe ↓',renderNote:'Rendering runs on this computer. Keep the editor server running.',shortcuts:'KEYBOARD SHORTCUTS',helpTitle:'Stay in the moment.',helpPlay:'Play / pause',helpTakes:'Veo · Kling · Seedance',helpSplit:'Split at the playhead',helpTrim:'Set source in / out',helpFrame:'Previous / next frame',helpUndo:'Undo (Shift to redo)',saved:'Saved locally',unsaved:'Local save unavailable',useTake:'Use this take',selected:'IN YOUR CUT',chosen:'Selected ✓',shots:'shots',export:'Export film ↗',exporting:'Rendering…',ready:'Your film is ready.',source:'Source',resetMessage:'Reset to Veo. You can undo this.',splitHint:'Place the playhead inside a shot to split it.',invalidTime:'Use MM:SS:FF (24 frames per second).',emptyDelete:'Keep at least one shot in your edit.',imported:'Edit opened.',exportFailed:'Export failed',loadFailed:'Start the local editor server, then open http://127.0.0.1:8787.\nCommand: python3 creative/editor/server.py',loadedError:'Could not load the video sources.',editWhileRendering:'This export uses the edit as it was when rendering started.',playError:'The browser could not start playback. Try Play again.'},
 fr:{eyebrow:'TROIS MODÈLES. VOTRE MONTAGE.',heading:'Gardez les moments qui comptent.',intro:'Comparez le même instant. Choisissez une prise. Créez votre film.',import:'Ouvrir un montage',save:'Sauvegarder',compare:'Comparer',program:'Votre film',soundOn:'Son activé',soundOff:'Son coupé',fit:'Ajuster la timeline',timeline:'LE MONTAGE',split:'Couper au curseur',zoom:'Zoom',sources:'PRISES SOURCES',yourCut:'VOTRE MONTAGE',sharedAudio:'SON COMMUN',audioDetail:'Une bande-son continue · musique + dialogues',timelineHint:'Cliquez sur une prise pour la choisir. Déplacez le curseur sur la règle.',previewHint:'Aperçu approximatif ; export découpé à l’image près.',selectedShot:'PLAN SÉLECTIONNÉ',take:'PRISE',sourceIn:'ENTRÉE SOURCE',sourceOut:'SORTIE SOURCE',applyTrim:'Appliquer le découpage',markIn:'Marquer entrée [I]',markOut:'Marquer sortie [O]',trimHint:'Timecode : minutes:secondes:images. L’image de sortie est exclue.',earlier:'← Avant',later:'Après →',remove:'Supprimer le plan',defaultNote:'Veo est votre point de départ. Remplacez un passage sans modifier les autres.',reset:'Revenir à toutes les prises Veo',backBoard:'Retour à la planche visuelle ↗',localNote:'Le montage reste dans ce navigateur. Partagez un fichier JSON avec votre équipe.',exportEyebrow:'DONNEZ VIE AU MONTAGE',exportTitle:'Vos meilleures prises, réunies.',render:'Générer le MP4',download:'Télécharger le film ↓',downloadRecipe:'Télécharger le montage JSON ↓',renderNote:'Le rendu tourne sur cet ordinateur. Laissez le serveur ouvert.',shortcuts:'RACCOURCIS CLAVIER',helpTitle:'Restez dans l’instant.',helpPlay:'Lecture / pause',helpTakes:'Veo · Kling · Seedance',helpSplit:'Couper au curseur',helpTrim:'Marquer entrée / sortie',helpFrame:'Image précédente / suivante',helpUndo:'Annuler (Maj pour rétablir)',saved:'Sauvegardé localement',unsaved:'Sauvegarde locale indisponible',useTake:'Choisir cette prise',selected:'DANS VOTRE FILM',chosen:'Sélectionnée ✓',shots:'plans',export:'Exporter le film ↗',exporting:'Rendu en cours…',ready:'Votre film est prêt.',source:'Source',resetMessage:'Montage Veo rétabli. Vous pouvez annuler.',splitHint:'Placez le curseur à l’intérieur d’un plan pour le couper.',invalidTime:'Utilisez MM:SS:II (24 images par seconde).',emptyDelete:'Gardez au moins un plan dans votre montage.',imported:'Montage ouvert.',exportFailed:'Échec du rendu',loadFailed:'Démarrez le serveur local, puis ouvrez http://127.0.0.1:8787.\nCommande : python3 creative/editor/server.py',loadedError:'Impossible de charger les vidéos.',editWhileRendering:'Cet export utilise le montage au moment du lancement du rendu.',playError:'Le navigateur n’a pas démarré la lecture. Réessayez avec Lecture.'}
};
let language='en';try{language=new URLSearchParams(location.search).get('lang')||localStorage.getItem(LANG)||'en';}catch{}if(!strings[language])language='en';
const t=k=>strings[language][k]||strings.en[k]||k;
let meta,project,selectedId,frame=0,playing=false,playOrigin=0,timeOrigin=0,raf=0,lastPlayingSegment=null,history=[],future=[],zoom=1,mode='compare',exportBusy=false,exportPoll=null;
const players=new Map();const audio=$('master-audio');let muted=false;
const clone=p=>JSON.parse(JSON.stringify(p));
const sourceLabel=s=>{let n=boundaries.findIndex((b,i)=>s.inFrame>=b&&s.inFrame<boundaries[i+1]);if(n<0)n=0;return labels[Math.min(n,labels.length-1)][language==='fr'?1:0];};
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,4000);}
function localSave(){try{localStorage.setItem(KEY,JSON.stringify(project));$('save-state').textContent=t('saved');}catch{$('save-state').textContent=t('unsaved');}}
function setLanguage(next){language=next;try{localStorage.setItem(LANG,next);}catch{}document.documentElement.lang=next;document.querySelectorAll('a[href*="category=animatic"]').forEach(a=>a.href='/creative/selection/index.html?category=animatic&lang='+next);document.querySelectorAll('[data-t]').forEach(el=>el.textContent=t(el.dataset.t));$('language').textContent=next==='en'?'FR':'EN';$('export-button').textContent=t('export');$('save-state').textContent=t('saved');$('sound').textContent=t(muted?'soundOff':'soundOn');if(project){renderTimeline();renderInspector();renderStatus();}}
function total(){return durationFrames(project);}
function current(){return locate(project,frame);}
function selected(){return timeline(project).find(s=>s.id===selectedId)||timeline(project)[0];}
function commit(next,message){try{validateProject(next,meta);if(JSON.stringify(next)===JSON.stringify(project)){if(message)toast(message);return;}pause();history.push(clone(project));if(history.length>100)history.shift();future=[];project=next;frame=Math.min(frame,total()-1);if(!project.segments.some(s=>s.id===selectedId))selectedId=current().id;const focus=selected();if(frame<focus.startFrame||frame>=focus.endFrame)frame=focus.startFrame;localSave();render();syncSources(true);if(message)toast(message);}catch(e){toast(e.message);}}
function undo(redo=false){const src=redo?future:history,dst=redo?history:future;if(!src.length)return;pause();dst.push(clone(project));project=src.pop();frame=Math.min(frame,total()-1);selectedId=current().id;localSave();render();syncSources(true);}
function choose(sourceId){if(!project)return;const s=selected();commit(setSource(project,s.id,sourceId));}
function seek(next,{select=true}={}){if(!project)return;pause();frame=Math.max(0,Math.min(total()-1,Math.round(next)));if(select)selectedId=current().id;syncSources(true);renderInspector();renderStatus();}
function syncSources(force=false){if(!project)return;const at=current().sourceFrame/24;for(const v of [...players.values(),audio]){if(v.readyState===0)continue;if(force||(!v.seeking&&Math.abs(v.currentTime-at)>.16)){try{v.currentTime=at;}catch{}}}lastPlayingSegment=current().id;}
function pause(){playing=false;cancelAnimationFrame(raf);for(const v of [...players.values(),audio])v.pause();$('play').textContent='▶';$('play').setAttribute('aria-label',language==='fr'?'Lecture':'Play');}
async function play(){if(!project)return;if(playing){pause();return;}if(frame>=total()-1)frame=0;selectedId=current().id;renderInspector();syncSources(true);playing=true;playOrigin=frame;timeOrigin=performance.now();$('play').textContent='Ⅱ';$('play').setAttribute('aria-label',language==='fr'?'Pause':'Pause');audio.muted=muted;const starts=await Promise.allSettled([...players.values(),audio].map(v=>v.play()));if(starts.every(r=>r.status==='rejected')){pause();toast(t('playError'));return;}tick();}
function tick(){if(!playing)return;frame=Math.min(total()-1,playOrigin+Math.floor((performance.now()-timeOrigin)*24/1000));const now=current();if(lastPlayingSegment!==now.id){const previous=timeline(project).find(s=>s.id===lastPlayingSegment);selectedId=now.id;syncSources(!previous||previous.outFrame!==now.inFrame);renderInspector();}else syncSources(false);renderStatus();if(frame>=total()-1){pause();return;}raf=requestAnimationFrame(tick);}
function renderStatus(){if(!project)return;const now=current();$('current-time').textContent=formatTime(frame);$('duration-time').textContent=formatTime(total());$('scene-label').textContent=String(now.index+1).padStart(2,'0')+' / '+project.segments.length+' · '+sourceLabel(now);for(const [id,v] of players){const tile=v.closest('.viewer');tile.classList.toggle('chosen',id===now.sourceId);tile.querySelector('.take-state').textContent=id===now.sourceId?t('selected'):'';tile.querySelector('[data-use]').textContent=id===selected().sourceId?t('chosen'):t('useTake');}
 const ruler=$('ruler');$('playhead').style.left=(ruler.offsetLeft+frame/total()*ruler.clientWidth)+'px';ruler.setAttribute('aria-valuenow',frame);ruler.setAttribute('aria-valuemax',total()-1);ruler.setAttribute('aria-valuetext',formatTime(frame));document.querySelectorAll('.take-block').forEach(b=>{b.classList.toggle('selected',b.dataset.id===selectedId);b.classList.toggle('playing-block',b.dataset.id===now.id);});}
function renderInspector(){if(!project)return;const s=selected();$('selected-index').textContent=String(s.index+1).padStart(2,'0')+' / '+project.segments.length;$('selected-name').textContent=sourceLabel(s);$('selected-summary').textContent=formatTime(s.durationFrames)+' · '+t('source')+' '+formatTime(s.inFrame)+' → '+formatTime(s.outFrame);$('take-select').value=s.sourceId;$('source-in').value=formatTime(s.inFrame);$('source-out').value=formatTime(s.outFrame);$('move-left').disabled=s.index===0;$('move-right').disabled=s.index===project.segments.length-1;$('delete-shot').disabled=project.segments.length===1;$('undo').disabled=!history.length;$('redo').disabled=!future.length;}
function block(s,sourceId,output=false){const active=s.sourceId===sourceId;const model=output?s.sourceId:sourceId;return `<button class="take-block ${model} ${active?'active-take':''}" style="width:${s.durationFrames/total()*100}%" data-id="${escape(s.id)}" ${output?'data-output="true"':`data-model="${sourceId}"`} title="${escape(sourceLabel(s)+' · '+names[model]+' · '+formatTime(s.inFrame)+'–'+formatTime(s.outFrame))}" aria-label="${escape(sourceLabel(s)+': '+names[model])}" aria-pressed="${active}"><span class="block-number">${String(s.index+1).padStart(2,'0')}</span><span class="block-title">${escape(output?names[model].split(' ')[0]:sourceLabel(s))}</span></button>`;}
function renderTimeline(){if(!project)return;const rows=timeline(project);$('shot-count').textContent=rows.length+' '+t('shots');$('source-tracks').innerHTML=order.map(id=>`<div class="source-row"><div class="track-label ${id}"><span class="model-dot"></span>${names[id]}</div><div class="track">${rows.map(s=>block(s,id)).join('')}</div></div>`).join('');$('output-track').innerHTML=rows.map(s=>block(s,s.sourceId,true)).join('');const step=zoom>=2?24:120;let ticks='';for(let n=0;n<total();n+=step)ticks+=`<div class="ruler-tick" style="left:${n/total()*100}%"><span>${Math.floor(n/24)}s</span></div>`;$('ruler').innerHTML=ticks;$('timeline-canvas').style.width=(zoom*100)+'%';renderStatus();}
function render(){renderTimeline();renderInspector();renderStatus();}
function parseTime(value){const m=value.trim().match(/^(\d{1,3}):([0-5]\d):([0-2]\d)$/);if(!m||+m[3]>=24)throw Error(t('invalidTime'));return (+m[1]*60 + +m[2])*24 + +m[3];}
function applyTrim(){try{const s=selected();commit(trimSegment(project,s.id,parseTime($('source-in').value),parseTime($('source-out').value)));}catch(e){toast(e.message);}}
function split(){const s=current();selectedId=s.id;const next=splitSegment(project,s.id,frame);selectedId=locate(next,frame).id;commit(next,next===project?t('splitHint'):null);selectedId=current().id;renderInspector();renderStatus();}
function mark(out){const s=selected(),now=current();if(s.id!==now.id){toast(t('splitHint'));return;}const value=now.sourceFrame+(out?1:0);$(out?'source-out':'source-in').value=formatTime(value);applyTrim();}
function downloadJSON(obj,name){const u=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
async function importFile(file){if(!file)return;try{if(file.size>500000)throw Error('Edit file is too large.');const p=JSON.parse(await file.text());validateProject(p,meta);commit(p,t('imported'));}catch(e){toast(e.message);}finally{$('project-file').value='';}}
function openExport(){pause();$('export-description').textContent=`${project.segments.length} ${t('shots')} · ${(total()/24).toFixed(2)} s · ${t('editWhileRendering')}`;$('export-dialog').showModal();}
async function startExport(){if(exportBusy)return;exportBusy=true;$('start-export').disabled=true;$('start-export').textContent=t('exporting');$('export-progress').hidden=false;$('export-progress').value=0;$('download-export').hidden=true;$('download-recipe').hidden=true;$('export-status').textContent=t('exporting');try{const response=await fetch('/api/export',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(project)});const data=await response.json();if(!response.ok)throw Error(data.error||response.statusText);pollExport(data.id);}catch(e){exportFailure(e.message);}}
function exportFailure(message){exportBusy=false;clearTimeout(exportPoll);$('start-export').disabled=false;$('start-export').textContent=t('render');$('export-status').textContent=t('exportFailed')+': '+message;}
async function pollExport(id){try{const response=await fetch('/api/export/'+encodeURIComponent(id));if(!response.ok)throw Error(response.statusText);const data=await response.json();$('export-progress').value=Number(data.progress)||0;$('export-status').textContent=t('exporting')+' '+Math.round(Number(data.progress)||0)+'%';if(data.status==='completed'){exportBusy=false;$('export-progress').value=100;$('export-status').textContent=t('ready');$('start-export').disabled=false;$('start-export').textContent=t('render');$('download-export').href=data.downloadUrl;$('download-export').download='converse-your-cut.mp4';$('download-export').hidden=false;if(data.recipeUrl){$('download-recipe').href=data.recipeUrl;$('download-recipe').download='converse-your-cut.json';$('download-recipe').hidden=false;}return;}if(data.status==='failed')throw Error(data.error||'Unknown render error');exportPoll=setTimeout(()=>pollExport(id),1000);}catch(e){exportFailure(e.message);}}
function setMode(next){mode=next;$('viewers').classList.toggle('program',next==='program');$('compare-mode').setAttribute('aria-pressed',next==='compare');$('program-mode').setAttribute('aria-pressed',next==='program');}
function rulerPointer(event){const box=$('ruler').getBoundingClientRect();seek((event.clientX-box.left)/box.width*total());}
function bind(){
 $('language').onclick=()=>setLanguage(language==='en'?'fr':'en');$('play').onclick=play;$('sound').onclick=()=>{muted=!muted;audio.muted=muted;$('sound').setAttribute('aria-pressed',!muted);$('sound').textContent=t(muted?'soundOff':'soundOn');};
 $('previous').onclick=()=>{const s=current();const rows=timeline(project);seek(frame>s.startFrame?s.startFrame:rows[Math.max(0,s.index-1)].startFrame);};$('next').onclick=()=>{const s=current();seek(timeline(project)[Math.min(s.index+1,project.segments.length-1)].startFrame);};
 $('take-select').onchange=e=>choose(e.target.value);$('apply-trim').onclick=applyTrim;$('mark-in').onclick=()=>mark(false);$('mark-out').onclick=()=>mark(true);$('split').onclick=split;$('undo').onclick=()=>undo();$('redo').onclick=()=>undo(true);
 $('move-left').onclick=()=>commit(moveSegment(project,selectedId,-1));$('move-right').onclick=()=>commit(moveSegment(project,selectedId,1));$('delete-shot').onclick=()=>commit(removeSegment(project,selectedId),project.segments.length===1?t('emptyDelete'):null);$('reset-project').onclick=()=>commit(createProject(meta),t('resetMessage'));
 $('zoom').oninput=e=>{zoom=+e.target.value;renderTimeline();};$('fit-view').onclick=()=>{zoom=1;$('zoom').value=1;renderTimeline();};$('compare-mode').onclick=()=>setMode('compare');$('program-mode').onclick=()=>setMode('program');
 $('source-tracks').onclick=e=>{const b=e.target.closest('[data-model]');if(!b)return;const s=timeline(project).find(s=>s.id===b.dataset.id);selectedId=s.id;seek(s.startFrame);choose(b.dataset.model);};$('output-track').onclick=e=>{const b=e.target.closest('[data-output]');if(!b)return;const s=timeline(project).find(s=>s.id===b.dataset.id);seek(s.startFrame);};
 $('ruler').onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();$('ruler').setPointerCapture(e.pointerId);rulerPointer(e);};$('ruler').onpointermove=e=>{if($('ruler').hasPointerCapture(e.pointerId))rulerPointer(e);};$('ruler').onpointerup=e=>{if($('ruler').hasPointerCapture(e.pointerId))$('ruler').releasePointerCapture(e.pointerId);};
 $('save-project').onclick=()=>downloadJSON(project,'converse-cut-'+new Date().toISOString().slice(0,10)+'.json');$('import-project').onclick=()=>$('project-file').click();$('project-file').onchange=e=>importFile(e.target.files[0]);
 $('export-button').onclick=openExport;$('start-export').onclick=startExport;$('close-export').onclick=()=>$('export-dialog').close();$('open-help').onclick=()=>$('help-dialog').showModal();$('close-help').onclick=()=>$('help-dialog').close();
 window.addEventListener('resize',renderStatus);window.addEventListener('keydown',e=>{if(!project||/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||document.querySelector('dialog[open]'))return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo(e.shiftKey);return;}if(e.metaKey||e.ctrlKey||e.altKey)return;const key=e.key.toLowerCase();if(key===' '){e.preventDefault();play();}else if(['1','2','3'].includes(key)){e.preventDefault();choose(order[Number(key)-1]);}else if(key==='s'){e.preventDefault();split();}else if(key==='i'||key==='o'){e.preventDefault();mark(key==='o');}else if(key==='arrowleft'||key==='arrowright'){e.preventDefault();seek(frame+(key==='arrowright'?1:-1)*(e.shiftKey?24:1));}});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
}
async function init(){setLanguage(language);try{if(location.protocol==='file:')throw Error(t('loadFailed'));const response=await fetch('/api/project');if(!response.ok)throw Error(t('loadedError'));meta=await response.json();project=createProject(meta);try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved){validateProject(saved,meta);project=saved;}}catch{}selectedId=project.segments[0].id;
 $('viewers').innerHTML=order.map(id=>{const s=meta.sources.find(s=>s.id===id);if(!s)throw Error('Missing source '+id);return `<article class="viewer ${id}"><div class="viewer-header"><span class="model-dot"></span>${names[id]}<span class="take-state"></span></div><video id="video-${id}" src="${escape(s.url)}" muted playsinline preload="auto" aria-label="${names[id]}"></video><div class="viewer-footer"><span class="source-duration">${formatTime(meta.durationFrames)} · ${order.indexOf(id)+1}</span><button data-use="${id}">${t('useTake')}</button></div></article>`;}).join('');
 for(const id of order){const v=$('video-'+id);v.muted=true;players.set(id,v);v.addEventListener('loadedmetadata',()=>{if(!playing)syncSources(true);});v.closest('.viewer').querySelector('[data-use]').onclick=()=>choose(id);v.onclick=()=>choose(id);v.addEventListener('error',()=>toast(names[id]+': '+t('loadedError')));}
 audio.src=meta.sources.find(s=>s.id==='veo31').url;audio.volume=.85;audio.addEventListener('loadedmetadata',()=>{if(!playing)syncSources(true);});bind();localSave();render();
 }catch(e){$('load-error').textContent=e.message+'\n'+(e.message===t('loadFailed')?'':t('loadFailed'));$('load-error').hidden=false;$('export-button').disabled=true;$('scene-label').textContent=t('loadedError');}}
init();
